Repository LXD-UMC-8th/FE-LXD, pull requests merged in 2025-07, with the labels that each got.

#74 [FEATURE]: ProvideCorrections 제작
  FE_LXD/src/App.tsx
  FE_LXD/src/components/Common/TitleHeader.tsx
  FE_LXD/src/components/Diary/DiaryContent.tsx
  FE_LXD/src/components/Diary/ProvideCorrections.tsx
  FE_LXD/src/index.css
  FE_LXD/src/pages/Diary/CorrectionsInDiaryDetail.tsx
  FE_LXD/src/pages/Diary/DiaryDetailPage.tsx
Labels: feat, FIX

#88 fix:서버와의 userInfo 교류를 위한 수정 및 리팩토링
  FE_LXD/src/App.tsx
  FE_LXD/src/components/Login/LangOptionsButton.tsx
  FE_LXD/src/pages/Login/LoginPage.tsx
  FE_LXD/src/pages/Login/ProfilePage.tsx
  FE_LXD/src/pages/Login/SignupFlow.tsx
  FE_LXD/src/pages/Login/SignupPage.tsx
  FE_LXD/src/utils/validate.ts
Labels: FIX

#100 [FIX]: CorrectionsPage
  src/components/Corrections/CorrectionComponent.tsx
  src/components/Corrections/ProfileInCorrections.tsx
  src/components/Corrections/Tabs/ProvidedCorrectionTab.tsx
  src/components/Corrections/Tabs/ReceivedCorrectionTab.tsx
  src/pages/Corrections/CorrectionsPage.tsx
Labels: design, FIX

#107 [API]: Corrections API 연결
  package-lock.json
  package.json
  src/App.tsx
  src/apis/axios.ts
  src/apis/correction.ts
  src/components/Corrections/CorrectionComponent.tsx
  src/components/Diary/CorrectionsInDiaryDetail.tsx
  src/components/Diary/ProvideCorrections.tsx
  src/context/translate.ts
  src/hooks/mutations/useGetCorrections.ts
  src/hooks/mutations/usePostCorrection.ts
  src/hooks/mutations/usePostLike.ts
  src/pages/Corrections/CorrectionsPage.tsx
  src/pages/Diary/DiaryDetailPage.tsx
  src/utils/types/correction.ts
  src/utils/types/member.ts
Labels: API
